using System;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;

namespace Horizon.Reflection
{
    /// <summary>
    /// Represents a cached <see cref="Assembly"/>.
    /// </summary>
    public class AssemblyData : MemberData
    {
        /// <summary>
        /// Cached <see cref="Assembly"/>.
        /// </summary>
        private readonly Assembly _assembly;

        /// <summary>
        /// Collection of every <see cref="Type"/> in the current <see cref="AssemblyData"/>.
        /// </summary>
        private readonly Lazy<IReadOnlyList<TypeData>> _types;

        /// <summary>
        /// Collection of every <see cref="AttributeData"/> applied to the current <see cref="AssemblyData"/>.
        /// </summary>
        private readonly Lazy<IReadOnlyList<AttributeData>> _attributes;

        /// <summary>
        /// The <see cref="XmlDocumentation"/> generated by the current <see cref="AssemblyData"/>.
        /// </summary>
        private readonly Lazy<XmlDocumentation> _xmlDocumentation;

        /// <summary>
        /// Creates a new instance of <see cref="AssemblyData"/>.
        /// </summary>
        /// <param name="assembly">Assembly.</param>
        internal AssemblyData(Assembly assembly) : base(assembly.GetName().Name, assembly.FullName)
        {
            _assembly = assembly;
            _types = new Lazy<IReadOnlyList<TypeData>>(() => _assembly.GetTypes().Select(type => type.GetTypeData()).ToArray());
            _attributes = new Lazy<IReadOnlyList<AttributeData>>(() => _assembly.GetCustomAttributes(true).Select(value => new AttributeData(value, value.GetType(), this)).ToArray());
            _xmlDocumentation = new Lazy<XmlDocumentation>(() => new XmlDocumentation(_assembly));
        }

        /// <inheritdoc cref="_types"/>
        public IReadOnlyList<TypeData> Types => _types.Value;

        ///<inheritdoc cref="_attributes"/>
        public override IReadOnlyList<AttributeData> Attributes => _attributes.Value;

        /// <inheritdoc cref="_xmlDocumentation"/>
        internal XmlDocumentation XmlDocumentation => _xmlDocumentation.Value;

        /// <summary>
        /// Implicitly converts the specified <see cref="AssemblyData"/> to <see cref="Assembly"/>.
        /// </summary>
        /// <param name="assemblyData">Assembly data.</param>
        /// <returns>Cached <see cref="Assembly"/>.</returns>
        public static implicit operator Assembly(AssemblyData assemblyData)
        {
            return assemblyData._assembly;
        }
    }
}